@baseUrl = http://localhost:3001/api/v1
@contentType = application/json

### login
# @name auth
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "amankriet@gmail.com",
    "password": "password2"
}

### signup
POST {{baseUrl}}/auth/signup
Content-Type: {{contentType}}

{
    "firstName": "Dhruv",
    "lastName": "Kumar",
    "email": "dhruv@gmail.com",
    "password": "dhruv",
    "mobile": 1111111111,
    "dob": "1998-01-20"
}

### logout
# @name auth
GET {{baseUrl}}/auth/logout
Authorization: {{auth.response.body.user.token}}

### get all users details
GET {{baseUrl}}/users/all?curPage=1&perPage=10
Authorization: {{auth.response.body.user.token}}

### get current user or user id details
GET {{baseUrl}}/users?id=65faf91627523044e548b12b
Authorization: {{auth.response.body.user.token}}

### update current user or user id data
PATCH {{baseUrl}}/users?id=65faf91627523044e548b12b
Authorization: {{auth.response.body.user.token}}
Content-Type: {{contentType}}

{
    "lastName": "Kumar"
}

### delete current user or user id
DELETE {{baseUrl}}/users
Authorization: {{auth.response.body.user.token}}

### get all expenses of current user
GET {{baseUrl}}/expenses/all?perPage=3&curPage=3
Authorization: {{auth.response.body.user.token}}

### get expense of current user or user id
GET {{baseUrl}}/expenses/
Authorization: {{auth.response.body.user.token}}

### create new expense for current user
POST {{baseUrl}}/expenses
Authorization: {{auth.response.body.user.token}}
Content-Type: {{contentType}}

{
    "title": "Snacks",
    "amount": 10,
    "date": "2024-01-20",
    "category": "Food and Drinks",
    "description": "test"
}

### update the existing expense of current user
PATCH {{baseUrl}}/expenses/{{auth.response.body.user.id}}

### delete the expense of current user
DELETE  {{baseUrl}}/expenses/{{auth.response.body.user.id}}

### delete all expense of current user
DELETE  {{baseUrl}}/expenses