@baseUrl = http://localhost:3001/api/v1
@contentType = application/json

### login
# @name auth
POST {{baseUrl}}/auth/login
Content-Type: {{contentType}}

{
    "email": "amankriet@gmail.com",
    "password": "password2"
}

> {% client.global.set("accessToken", response.body.user.accessToken); %}

### signup
POST {{baseUrl}}/auth/signup
Content-Type: {{contentType}}

{
    "firstName": "Dhruv",
    "lastName": "Kumar",
    "email": "dhruv@gmail.com",
    "password": "dhruv",
    "mobile": 1111111111,
    "dob": "1998-01-20"
}

### logout
# @name auth
GET {{baseUrl}}/auth/logout
Authorization: {{accessToken}}

> {% client.global.set("accessToken", response.body.token); %}

### Refresh Token
# @name refreshToken
GET {{baseUrl}}/auth/refresh-token
Authorization: {{accessToken}}

> {% client.global.set("accessToken", response?.body?.accessToken); %}

### get all users details
GET {{baseUrl}}/users/all?page=1&limit=10
Authorization: {{accessToken}}

### get current user or user id details
GET {{baseUrl}}/users?id=65faf91627523044e548b12b
Authorization: {{accessToken}}

### update current user or user id data
PATCH {{baseUrl}}/users?id=65faf91627523044e548b12b
Authorization: {{accessToken}}
Content-Type: {{contentType}}

{
    "lastName": "Kumar"
}

### delete current user or user id
DELETE {{baseUrl}}/users?id=66159f334180d2a1a6fa2b73
Authorization: {{auth.response.body.user.token}}

### get all expenses of current user
GET {{baseUrl}}/expenses/all?page=3&limit=3
Authorization: {{auth.response.body.user.token}}

### get expense of current user or user id
GET {{baseUrl}}/expenses?id=660ee74f548451accf013d35
Authorization: {{auth.response.body.user.token}}

### create new expense for current user
POST {{baseUrl}}/expenses
Authorization: {{auth.response.body.user.token}}
Content-Type: {{contentType}}

{
    "title": "Snacks",
    "amount": 10,
    "date": "2024-01-20",
    "category": "Food and Drinks",
    "description": "test"
}

### update the existing expense of current user
PATCH {{baseUrl}}/expenses

### delete the expense of current user
DELETE  {{baseUrl}}/expenses

### delete all expense of current user
DELETE  {{baseUrl}}/expenses