@baseUrl = http://localhost:3001/api/v1
@contentType = application/json

### @name login
POST {{baseUrl}}/login
Content-Type: {{contentType}}

{
    "email": "abc@123.com",
    "password": "password1"
}

### signup
POST {{baseUrl}}/signup
Content-Type: {{contentType}}

{
    "firstName": "Aman",
    "lastName": "Kumar",
    "email": "abc@123.com",
    "password": "password1",
    "mobile": 8439775478,
    "dob": "1998-01-19"
}

### logout
GET {{baseUrl}}/logout

### get all user details
GET {{baseUrl}}/users/

### get user details
GET {{baseUrl}}/users/id

### create user
POST {{baseUrl}}/users/

### update user
PATCH {{baseUrl}}/users/id

### delete user
DELETE {{baseUrl}}/users/

### delete user
DELETE {{baseUrl}}/users/id

### get all expenses of current user
GET {{baseUrl}}/expenses/

### get expense of current user
GET {{baseUrl}}/expenses/id

### create new expenses of current user
POST {{baseUrl}}/expenses/

### update the existing expense of current user
PATCH {{baseUrl}}/expenses/id

### delete the expense of current user
DELETE  {{baseUrl}}/expenses/id

### delete all expenses of current user
DELETE  {{baseUrl}}/expenses/